"""add image and history tables

Revision ID: 6837439a89aa
Revises: 20e0f20942cb
Create Date: 2022-05-19 23:22:31.478350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6837439a89aa'
down_revision = '20e0f20942cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('uploaded_date', sa.DateTime(), nullable=True),
    sa.Column('wrinkle', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_image_id', sa.Integer(), nullable=False),
    sa.Column('modified_image_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modified_image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['original_image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_id'), 'history', ['id'], unique=False)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'type')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('type', postgresql.ENUM('normal', 'super', name='type'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_index(op.f('ix_history_id'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
